version: "3.7"
services:
  swagger:
    image: swaggerapi/swagger-ui
    volumes:
      - ./docs/api:/usr/share/nginx/html/api
    environment:
      URLS: "[ { url: \"api/swagger.yml\", name: \"DePay API\" } ]"
    ports:
      - "8080:8080"