version: "3.7"
services:
  swagger:
    image: swaggerapi/swagger-ui
    volumes:
      - ./docs/swagger.yml:/usr/share/nginx/html/swagger.yml
    environment:
      URLS: "[ { url: \"swagger.yml\", name: \"DePay API\" } ]"
    ports:
      - "8080:8080"