openapi: 3.0.3
info:
  version: 1.0.0
  title: Customer API
# servers: // set base url
#   - url: /customer/
#     description: Local
tags:
  - name: balance
    description: 残高
  - name: charges
    description: チャージ
paths:
  # balance
  /balance:
    $ref: './path/balance/index.yml'
  # charges
  /charges:
    $ref: './path/charges/index.yml'
# components: security...?
#   securitySchemes:
#     basicAuth:
#         type: http
#         scheme: basic
#     cookieAuth:
#         type: apiKey
#         in: header
#         name: _depay