swagger: "2.0"
info:
  version: 1.0.0
  title: Customer API
consumes:
  - application/json
produces:
  - application/json
tags:
  - name: auth
    description: 認証
  - name: balance
    description: 残高
  - name: charges
    description: チャージ
  - name: payouts
    description: 支払い
  - name: transactions
    description: 取引履歴
paths:
  /balance:
    $ref: './path/balance/index.yml'